version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.2.1

    steps:
    - checkout

    - run:
        name: Install sbt
        command: |
          curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
          sudo dpkg -i sbt-$SBT_VERSION.deb
          rm sbt-$SBT_VERSION.deb
          sudo apt-get update
          sudo apt-get install -y sbt

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: cat /dev/null | sbt test:compile

    - save_cache:
        paths:
        - ~/.m2
        - ~/.sbt
        key: v1-dependencies--{{ checksum "build.sbt" }}

    # run tests!
    - run: cat /dev/null | sbt test:test

    # package jar
    - run: cat /dev/null | sbt package

    # ToDo: Build and push docker to docker registry
    # docker build --build-arg VERSION=x.y.z -t sparkx:x.y.z .